//go:build !ignore_autogenerated

// Manually written deep copy functions following controller-gen conventions.
// When controller-gen is wired in the Makefile (Session N), this file will be
// replaced by the generated output. Until then these implementations are
// hand-maintained and must be kept in sync with the type definitions.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of RBACPolicySpec into another RBACPolicySpec instance.
func (in *RBACPolicySpec) DeepCopyInto(out *RBACPolicySpec) {
	*out = *in
	if in.AllowedClusters != nil {
		in, out := &in.AllowedClusters, &out.AllowedClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of RBACPolicySpec.
func (in *RBACPolicySpec) DeepCopy() *RBACPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RBACPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of RBACPolicyStatus into another RBACPolicyStatus instance.
func (in *RBACPolicyStatus) DeepCopyInto(out *RBACPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of RBACPolicyStatus.
func (in *RBACPolicyStatus) DeepCopy() *RBACPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RBACPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of RBACPolicy into another RBACPolicy instance.
func (in *RBACPolicy) DeepCopyInto(out *RBACPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of RBACPolicy.
func (in *RBACPolicy) DeepCopy() *RBACPolicy {
	if in == nil {
		return nil
	}
	out := new(RBACPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object for RBACPolicy.
func (in *RBACPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of RBACPolicyList into another RBACPolicyList instance.
func (in *RBACPolicyList) DeepCopyInto(out *RBACPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RBACPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of RBACPolicyList.
func (in *RBACPolicyList) DeepCopy() *RBACPolicyList {
	if in == nil {
		return nil
	}
	out := new(RBACPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object for RBACPolicyList.
func (in *RBACPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
